// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnomumzambsuooclxddh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJub211bXphbWJzdW9vY2x4ZGRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4OTg3NzEsImV4cCI6MjA2NDQ3NDc3MX0._aA1WsscaJf12xKsq7YFfhHjyBK1BBjq3AtuupTJzh4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);